name: india-cov19-statewide-current-status-update

on:
  push: # run jobs on push
  schedule:
    - cron: "0 5,16 * * *" # runs at 5:00 AM UTC (10.30 AM IST) & 4:00 PM UTC (9.30 PM IST) everyday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run python script to get the latest data
        run: |
          cd 01_ETL/
          python india_statewide_daily_covid_data_etl.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a
      - name: push changes
        uses: ad-m/github-push-action@master #v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
